import { TABLES } from './config/tables.js';
import { SLOTS, STATUS, BLOCKS, COLORS, DAYS, MONTHS, PLAN } from './config/constants.js';
import { state } from './state/store.js';
import { $, $$, toast, sync } from './utils/dom.js';
import { esc, badgeStyle } from './utils/format.js';
import { iso, dateObj, dayRu, mondayOf, nextMonday } from './utils/dates.js';
import { generatePassword, copyText } from './utils/password.js';
import { initSupabase } from './services/client.js';
import { invokeAdminFunction } from './services/admin-auth.js';
import { logEvent, logError } from './services/logs.js';

const baseMonday = () => { const dates=state.posts.filter(p=>!p.is_deleted&&p.post_date).map(p=>dateObj(p.post_date)).filter(Boolean).sort((a,b)=>a-b); return dates.length ? mondayOf(dates[0]) : mondayOf(nextMonday()); };
const weekFor = s => { const d=dateObj(s); if(!d) return 1; return Math.max(1, Math.floor((mondayOf(d)-baseMonday())/604800000)+1); };
const slotOrder = k => Number(dict('slot',k)?.sort_order || SLOTS[k]?.[1] || 99);
const normalize = p => { p={...p}; p.post_date = p.post_date ? String(p.post_date).slice(0,10) : null; p.day_name = p.post_date ? dayRu(p.post_date) : null; p.week_no = p.post_date ? weekFor(p.post_date) : Number(p.week_no||1); p.slot_order = slotOrder(p.slot); p.is_deleted=!!p.is_deleted; return p; };
const dictItems = cat => state.dicts.filter(x=>x.category===cat&&x.is_active!==false).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||String(a.label).localeCompare(String(b.label),'ru'));
const dict = (cat,key) => dictItems(cat).find(x=>x.item_key===key);
const label = (cat,key,fallback='') => dict(cat,key)?.label || fallback || key || '—';
const hex = (cat,key) => dict(cat,key)?.color_hex || COLORS[key] || '#1f5f5b';
const tagsForBlock = block => state.tags.filter(t=>t.block===block&&t.is_active!==false).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));
const canAdmin = () => state.profile?.role==='admin';
const can = k => canAdmin() || !!state.profile?.[k];
const canManage = () => canAdmin() || !!state.profile?.can_manage_users;
const tagAllowed = tag => !state.profile?.allowed_hashtags?.length || !tag || state.profile.allowed_hashtags.includes(tag);
const isIdea = p => !p?.post_date || (p.status==='idea' && Number(p.week_no||0)>3);
const canReadPost = p => canAdmin() || ((isIdea(p)?state.profile?.can_read_ideas:state.profile?.can_read_posts) && (state.profile?.data_scope==='all'||p.user_id===state.user?.id) && tagAllowed(p.hashtag));
const canEditPost = p => canAdmin() || ((isIdea(p)?state.profile?.can_edit_ideas:state.profile?.can_edit_posts) && (state.profile?.data_scope==='all'||p.user_id===state.user?.id) && tagAllowed(p.hashtag));

window.addEventListener('error', e=>logError(e.error||e.message,'window.onerror'));
window.addEventListener('unhandledrejection', e=>logError(e.reason,'unhandledrejection'));

function initClient(){ try{ initSupabase(); return true; } catch(e){ $('#authMessage').textContent=e.message; return false; } }
export async function boot(){ if(!initClient()) return; wire(); const {data}=await state.sb.auth.getSession(); if(data?.session?.user){ state.user=data.session.user; await enterApp(); } }
function wire(){
  $('#loginForm').addEventListener('submit', async e=>{ e.preventDefault(); await login(); });
  $('#logoutBtn').onclick=logout; $('#newPostBtn').onclick=()=>openPostModal(); $('#seedBtn').onclick=seedPlan; $('#excelBtn').onclick=openExcelModal; $('#saveAllBtn').onclick=saveAllDirty;
  $('#tabs').addEventListener('click', e=>{ const b=e.target.closest('button[data-tab]'); if(b) switchTab(b.dataset.tab); });
  ['filterWeek','filterBlock','filterStatus','searchInput'].forEach(id=>$('#'+id).addEventListener('input',()=>{ state.filters={week:$('#filterWeek').value,block:$('#filterBlock').value,status:$('#filterStatus').value,q:$('#searchInput').value.trim().toLowerCase()}; logEvent('filter_change','ui',null,state.filters); render(); }));
  document.addEventListener('click', e=>{ const c=e.target.closest('[data-close]'); if(c) closeModal(c.dataset.close); });
  window.addEventListener('beforeunload', e=>{ if(state.dirty.size){ e.preventDefault(); e.returnValue=''; } });
}
async function login(){ try{ const email=$('#loginEmail').value.trim(); const password=$('#loginPassword').value; $('#authMessage').textContent=''; const {data,error}=await state.sb.auth.signInWithPassword({email,password}); if(error){ $('#authMessage').textContent=error.message; return; } state.user=data.user; await logEvent('login','auth'); await enterApp(); }catch(e){ $('#appView').classList.add('hidden'); $('#authView').classList.remove('hidden'); $('#authMessage').textContent=e.message||String(e); await logError(e,'login'); } }
async function logout(){ if(state.dirty.size && !confirm('Есть несохранённые изменения. Выйти?')) return; await logEvent('logout','auth'); await state.sb.auth.signOut(); location.reload(); }
async function enterApp(){ await loadAll(); $('#authView').classList.add('hidden'); $('#appView').classList.remove('hidden'); sync('загрузка...'); $('#userBadge').textContent=`${state.user.email} · ${state.profile.role}`; $('#accessTab').classList.toggle('hidden',!canManage()); $('#logsTab').classList.toggle('hidden',!canManage()); fillFilters(); render(); sync('загружено','ok'); await logEvent('app_open','ui'); }
async function loadAll(){
  const prof=await state.sb.from(TABLES.profiles).select('*').order('email'); if(prof.error) throw prof.error; state.profiles=prof.data||[]; state.profile=state.profiles.find(p=>String(p.email).toLowerCase()===String(state.user.email).toLowerCase()); if(!state.profile||!state.profile.is_active) throw new Error('Нет активного профиля доступа. Создай пользователя в pulse_profiles.');
  const [dicts,tags,posts,mats] = await Promise.all([
    state.sb.from(TABLES.dicts).select('*').order('category').order('sort_order'), state.sb.from(TABLES.tags).select('*').order('sort_order'), state.sb.from(TABLES.posts).select('*').eq('is_deleted',false).order('post_date',{ascending:true,nullsFirst:false}).order('slot_order'), state.sb.from(TABLES.materials).select('*').eq('is_deleted',false).order('created_at',{ascending:false})
  ]);
  [dicts,tags,posts,mats].forEach(r=>{ if(r.error) throw r.error; });
  state.dicts=dicts.data||[]; state.tags=tags.data||[]; state.posts=(posts.data||[]).map(normalize); state.materials=mats.data||[]; state.selectedPost=filteredPosts()[0]?.id||null;
}
function fillFilters(){ const opt=(items,all='Все')=>`<option value="all">${all}</option>`+items.map(x=>`<option value="${esc(x.item_key||x[0])}">${esc(x.label||x[1])}</option>`).join(''); $('#filterBlock').innerHTML=opt(dictItems('block').length?dictItems('block'):Object.entries(BLOCKS).map(([item_key,label])=>({item_key,label}))); $('#filterStatus').innerHTML=opt(dictItems('status').length?dictItems('status'):Object.entries(STATUS).map(([item_key,label])=>({item_key,label}))); }
function filteredPosts(){ const f=state.filters; return state.posts.filter(p=>!p.is_deleted&&canReadPost(p)).filter(p=>f.week==='all'||String(p.week_no)===f.week).filter(p=>f.block==='all'||p.block===f.block).filter(p=>f.status==='all'||p.status===f.status).filter(p=>!f.q||[p.topic,p.hashtag,p.goal,p.cta,p.content_text,p.notes,p.owner,p.post_date].join(' ').toLowerCase().includes(f.q)).sort(sortPost); }
const sortPost=(a,b)=>(a.post_date||'9999-99-99').localeCompare(b.post_date||'9999-99-99')||slotOrder(a.slot)-slotOrder(b.slot)||(a.sort_order||0)-(b.sort_order||0);
function render(){ $('#saveAllBtn').classList.toggle('hidden',!state.dirty.size); const fn={plan:renderPlan,calendar:renderCalendar,bank:renderBank,materials:renderMaterials,dicts:renderDicts,access:renderAccess,logs:renderLogs}[state.activeTab]; fn?.(); }
function switchTab(tab){ state.activeTab=tab; $$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); logEvent('tab_switch','ui',null,{tab}); render(); }
function layout(leftTitle,left,rightTitle,right){ $('#workspace').innerHTML=`<section class="layout"><div class="panel list-panel"><div class="panel-head"><div class="panel-title">${leftTitle}</div></div><div class="panel-body">${left}</div></div><div class="panel editor-panel"><div class="panel-head"><div class="panel-title">${rightTitle}</div></div><div class="panel-body">${right}</div></div></section>`; }
function renderPlan(){ const f=filteredPosts().filter(p=>p.post_date); let html='',last=''; f.forEach(p=>{ const g=`Неделя ${p.week_no} · ${p.day_name} · ${p.post_date}`; if(g!==last){ html+=`<div class="day-head"><span>${esc(g)}</span><span>${postsByDate(p.post_date).length} пост(ов)</span></div>`; last=g; } html+=rowHtml(p); }); layout('Контент-план',html||'<div class="empty">Нет постов</div>','Карточка поста',postEditor()); bindPostRows(); bindPostEditor(); }
function rowHtml(p){ return `<div class="post-row ${state.selectedPost===p.id?'selected':''} ${state.dirty.has(p.id)?'dirty':''}" data-id="${p.id}"><div><div>${esc(label('slot',p.slot,SLOTS[p.slot]?.[0]))}${state.dirty.has(p.id)?'<span class="dot"></span>':''}</div><div class="small muted">нед. ${p.week_no}</div></div><div><span class="badge" style="${badgeStyle(hex('block',p.block))}">${esc(label('block',p.block,BLOCKS[p.block]))}</span></div><div><div class="topic">${esc(p.topic)}</div><div class="hashtag">${esc(p.hashtag||'')}</div></div><div><span class="badge" style="${badgeStyle(hex('status',p.status))}">${esc(label('status',p.status,STATUS[p.status]))}</span></div><div class="small muted">${esc(p.owner||'')}</div></div>`; }
function bindPostRows(){ $$('.post-row').forEach(r=>r.onclick=()=>{ state.selectedPost=r.dataset.id; logEvent('open_post','post',state.selectedPost); render(); }); }
function selectedPost(){ return state.posts.find(p=>p.id===state.selectedPost); }
function postEditor(){
  const p=selectedPost();
  if(!p) return '<div class="empty">Выберите пост</div>';
  const disabled=canEditPost(p)?'':'disabled';
  return `${!canEditPost(p)?'<div class="message">Только чтение</div>':''}
  <div class="form-row"><label>Тема</label><input value="${esc(p.topic)}" data-post-field="topic" ${disabled}></div>
  <div class="grid2"><div class="form-row"><label>Дата</label>${postDateField(p,disabled)}</div><div class="form-row"><label>Слот</label><select data-post-field="slot" ${disabled}>${opts('slot',p.slot,SLOTS)}</select></div></div>
  <div class="grid2"><div class="form-row"><label>Статус</label><select data-post-field="status" ${disabled}>${opts('status',p.status,STATUS)}</select></div><div class="form-row"><label>Блок</label><select data-post-field="block" ${disabled}>${opts('block',p.block,BLOCKS)}</select></div></div>
  <div class="form-row"><label>Хэштег</label><select data-post-field="hashtag" ${disabled}>${tagOptions(p.block,p.hashtag)}</select></div>
  <div class="form-row"><label>Цель</label><input value="${esc(p.goal||'')}" data-post-field="goal" ${disabled}></div>
  <div class="grid2"><div class="form-row"><label>Формат</label><input value="${esc(p.format||'')}" data-post-field="format" ${disabled}></div><div class="form-row"><label>Аудитория</label><input value="${esc(p.audience||'')}" data-post-field="audience" ${disabled}></div></div>
  <div class="form-row"><label>CTA</label><input value="${esc(p.cta||'')}" data-post-field="cta" ${disabled}></div>${materialsBox(p)}
  <div class="grid2 compact-text-row"><div class="form-row"><label>Текст поста</label><textarea data-post-field="content_text" ${disabled}>${esc(p.content_text||'')}</textarea></div><div class="form-row"><label>Заметки</label><textarea data-post-field="notes" ${disabled}>${esc(p.notes||'')}</textarea></div></div>
  <div class="save-line"><span class="hint">${state.dirty.has(p.id)?'Есть несохранённые изменения':'Изменений нет'}</span><button class="btn primary" id="savePostBtn" ${state.dirty.has(p.id)&&canEditPost(p)?'':'disabled'}>Сохранить</button></div>
  <div class="actions" style="margin-top:8px"><button class="btn" id="dupPostBtn">Дублировать</button><button class="btn danger" id="deletePostBtn" ${canEditPost(p)?'':'disabled'}>Скрыть</button></div>`;
}

function postDateField(p, disabled){
  const labelText = p.post_date ? `${p.post_date} · ${dayRu(p.post_date)}` : 'дата не выбрана';
  const open = state.datePicker?.postId === p.id;
  return `<div class="date-field-wrap">
    <button class="date-display" type="button" id="postDateToggle" ${disabled}>
      <span class="date-display-main"><span class="date-display-date">${esc(labelText)}</span><span class="date-display-sub">календарь со слотами и хэштегами</span></span>
      <span class="date-display-icon">▾</span>
    </button>
    ${open ? pubDatePicker(p) : ''}
    <div class="shift-quick-row"><button class="btn" type="button" id="shiftPostDay" ${canEditPost(p)?'':'disabled'}>+1 день</button><button class="btn" type="button" id="shiftPostWeek" ${canEditPost(p)?'':'disabled'}>+1 неделя</button></div>
  </div>`;
}

function pickerMonthStart(p){
  const raw = state.datePicker?.month || p.post_date || iso(nextMonday());
  const d = dateObj(raw) || nextMonday();
  return new Date(d.getFullYear(), d.getMonth(), 1);
}
function pubDatePicker(p){
  const m=pickerMonthStart(p);
  const start=mondayOf(new Date(m.getFullYear(),m.getMonth(),1));
  const cells=[];
  for(let i=0;i<42;i++){ const d=new Date(start); d.setDate(start.getDate()+i); cells.push(pubDateCell(d,p,m.getMonth())); }
  return `<div class="pub-calendar-pop"><div class="pub-cal-head"><button class="btn" type="button" id="pubPrevMonth">←</button><div class="pub-cal-title">${MONTHS[m.getMonth()]} ${m.getFullYear()}</div><div class="pub-cal-actions"><button class="btn" type="button" id="pubNextMonth">→</button><button class="btn" type="button" id="pubClosePicker">×</button></div></div><div class="pub-cal-week"><div>Пн</div><div>Вт</div><div>Ср</div><div>Чт</div><div>Пт</div><div>Сб</div><div>Вс</div></div><div class="pub-cal-grid">${cells.join('')}</div><div class="pub-cal-legend"><span><i class="pub-dot same"></i> текущий хэштег занят</span><span><i class="pub-dot occupied"></i> другие публикации внутри дня</span><span><i class="pub-dot free"></i> текущий хэштег свободен</span><span class="tag">v42-card-v23</span></div></div>`;
}
function pubDateCell(day,p,monthIndex){
  const ds=iso(day);
  const sameHash=String(p.hashtag||'').trim();
  const dayPosts=postsByDate(ds).filter(x=>x.id!==p.id);
  const same=dayPosts.filter(x=>String(x.hashtag||'').trim()===sameHash && sameHash);
  const otherPosts=dayPosts.filter(x=>!(String(x.hashtag||'').trim()===sameHash && sameHash));
  const other=day.getMonth()!==monthIndex;
  const hashState=same.length?'same':'available';
  const badges=[];
  if(same.length) badges.push(`<span class="pub-badge same" title="Этот же хэштег уже стоит в этот день">хэштег занят</span>`);
  otherPosts.slice(0,3).forEach(x=>badges.push(`<span class="pub-badge other-slot" title="${esc(label('slot',x.slot,SLOTS[x.slot]?.[0]))} · ${esc(x.hashtag||'')}">${esc(label('slot',x.slot,SLOTS[x.slot]?.[0]))} · ${esc(x.hashtag||'без хэштега')}</span>`));
  if(otherPosts.length>3) badges.push(`<span class="pub-badge other-slot">+${otherPosts.length-3} ещё</span>`);
  const dayStyle=hashState==='same'
    ? 'background:#ffe6df!important;border-color:#df6b4f!important;color:#8f1a1a!important;'
    : 'background:#eaf8f0!important;border-color:#74c991!important;color:#174f2f!important;';
  return `<button type="button" class="pub-day ${other?'other':''} hash-${hashState} ${ds===p.post_date?'current':''}" data-date="${ds}" data-hash-state="${hashState}" style="${dayStyle}"><div class="pub-day-num"><b>${day.getDate()}</b><span>${dayRu(ds)}</span></div>${badges.join('')}</button>`;
}
function bindPostEditor(){
  const p=selectedPost();
  if(!p) return;
  $$('[data-post-field]').forEach(el=>{ el.onchange=()=>editPostField(p.id,el.dataset.postField,el.value); });
  $('#postDateToggle')?.addEventListener('click',()=>togglePostDatePicker(p.id));
  $('#pubClosePicker')?.addEventListener('click',()=>{ state.datePicker=null; render(); });
  $('#pubPrevMonth')?.addEventListener('click',()=>movePostDatePickerMonth(-1));
  $('#pubNextMonth')?.addEventListener('click',()=>movePostDatePickerMonth(1));
  $$('.pub-day[data-date]').forEach(b=>b.addEventListener('click',()=>{ state.datePicker=null; editPostField(p.id,'post_date',b.dataset.date); }));
  $('#shiftPostDay')?.addEventListener('click',()=>shiftPostDate(p.id,1));
  $('#shiftPostWeek')?.addEventListener('click',()=>shiftPostDate(p.id,7));
  $('#savePostBtn')?.addEventListener('click',()=>savePost(p.id));
  $('#dupPostBtn')?.addEventListener('click',()=>duplicatePost(p.id));
  $('#deletePostBtn')?.addEventListener('click',()=>deletePost(p.id));
  $$('.add-material-inline').forEach(b=>b.onclick=()=>openMaterialModal(null,p.id));
}
function togglePostDatePicker(id){
  const p=state.posts.find(x=>x.id===id);
  if(!p || !canEditPost(p)) return;
  if(state.datePicker?.postId===id){ state.datePicker=null; render(); return; }
  const d=dateObj(p.post_date)||nextMonday();
  state.datePicker={postId:id,month:iso(new Date(d.getFullYear(),d.getMonth(),1))};
  render();
}
function movePostDatePickerMonth(delta){
  if(!state.datePicker) return;
  const d=dateObj(state.datePicker.month)||new Date();
  d.setMonth(d.getMonth()+delta);
  state.datePicker.month=iso(new Date(d.getFullYear(),d.getMonth(),1));
  render();
}
function shiftPostDate(id,days){
  const p=state.posts.find(x=>x.id===id);
  if(!p || !canEditPost(p) || !p.post_date) return;
  const d=dateObj(p.post_date); d.setDate(d.getDate()+days);
  editPostField(id,'post_date',iso(d));
}
function opts(cat,cur,fallback){ const rows=dictItems(cat); const arr=rows.length?rows.map(x=>[x.item_key,x.label]):Object.entries(fallback); return arr.map(([k,v])=>`<option value="${esc(k)}" ${k===cur?'selected':''}>${esc(Array.isArray(v)?v[0]:v)}</option>`).join(''); }
function tagOptions(block,cur){ let arr=tagsForBlock(block); if(cur&&!arr.find(t=>t.hashtag===cur)) arr=[{hashtag:cur},...arr]; return arr.map(t=>`<option value="${esc(t.hashtag)}" ${t.hashtag===cur?'selected':''}>${esc(t.hashtag)}</option>`).join(''); }
function editPostField(id,field,value){ const p=state.posts.find(x=>x.id===id); if(!p||!canEditPost(p)) return; if(field==='block'){ p.block=value; p.hashtag=tagsForBlock(value)[0]?.hashtag||p.hashtag; } else if(field==='post_date'){ p.post_date=value||null; } else { p[field]=value; } Object.assign(p, normalize(p)); state.dirty.add(id); sync(`${state.dirty.size} несохран.`,'saving'); logEvent('field_change','post',id,{field,value}); render(); }
function postPayload(p){ const n=normalize(p); return {week_no:n.week_no,post_date:n.post_date,day_name:n.day_name,slot:n.slot,slot_order:n.slot_order,block:n.block,hashtag:n.hashtag,topic:n.topic,goal:n.goal,format:n.format,cta:n.cta,audience:n.audience,status:n.status,owner:n.owner,content_text:n.content_text,notes:n.notes,is_deleted:n.is_deleted,sort_order:n.sort_order,updated_at:new Date().toISOString()}; }
async function savePost(id){ const p=state.posts.find(x=>x.id===id); if(!p) return; sync('сохранение...','saving'); const {error}=await state.sb.from(TABLES.posts).update(postPayload(p)).eq('id',id); if(error){ toast(error.message,'error'); await logError(error,'savePost'); return; } state.dirty.delete(id); await logEvent('save_post','post',id,postPayload(p)); sync('сохранено','ok'); toast('Пост сохранён','ok'); render(); }
async function saveAllDirty(){ for(const id of [...state.dirty]) await savePost(id); }
async function duplicatePost(id){ const p=state.posts.find(x=>x.id===id); if(!p) return; const copy=postPayload({...p,id:undefined,topic:p.topic+' — копия',status:'idea',user_id:state.user.id,owner:state.profile.display_name||state.user.email,sort_order:state.posts.length+1}); copy.user_id=state.user.id; const {data,error}=await state.sb.from(TABLES.posts).insert(copy).select().single(); if(error){toast(error.message,'error'); return;} state.posts.push(normalize(data)); state.selectedPost=data.id; await logEvent('duplicate_post','post',id,{new_id:data.id}); render(); }
async function deletePost(id){ if(!confirm('Скрыть пост?')) return; const p=state.posts.find(x=>x.id===id); p.is_deleted=true; await savePost(id); state.posts=state.posts.filter(x=>x.id!==id); state.selectedPost=filteredPosts()[0]?.id||null; await logEvent('delete_post','post',id); render(); }
function materialsBox(p){ const rows=state.materials.filter(m=>m.post_id===p.id&&!m.is_deleted); return `<div class="material-box"><div class="save-line"><span class="section-label">Материалы к посту</span><button class="btn add-material-inline" type="button">+ ссылка</button></div>${rows.map(m=>`<a class="material-line" href="${esc(safeHref(m.url))}" target="_blank">${esc(m.title||m.url)}</a>`).join('')||'<div class="hint">Нет материалов</div>'}</div>`; }
function safeHref(u){ u=String(u||'').trim(); return !u?'#':/^https?:\/\//i.test(u)?u:'https://'+u; }
function postsByDate(ds){ return state.posts.filter(p=>!p.is_deleted&&p.post_date===ds&&canReadPost(p)).sort(sortPost); }
function renderCalendar(){ $('#workspace').innerHTML=`<section class="layout"><div class="panel calendar-panel"><div class="cal-nav"><button class="btn" id="prevMonth">←</button><div class="cal-title">${MONTHS[state.calDate.getMonth()]} ${state.calDate.getFullYear()}</div><button class="btn" id="nextMonth">→</button></div><div class="cal-week"><div>Пн</div><div>Вт</div><div>Ср</div><div>Чт</div><div>Пт</div><div>Сб</div><div>Вс</div></div><div class="cal-grid">${calendarCells()}</div></div><div class="panel editor-panel"><div class="panel-head"><div class="panel-title">Карточка поста</div></div><div class="panel-body">${postEditor()}</div></div></section>`; $('#prevMonth').onclick=()=>{state.calDate.setMonth(state.calDate.getMonth()-1); render();}; $('#nextMonth').onclick=()=>{state.calDate.setMonth(state.calDate.getMonth()+1); render();}; $$('.cal-cell[data-date]').forEach(c=>c.onclick=()=>openDayDrawer(c.dataset.date)); bindPostEditor(); }
function calendarCells(){ const y=state.calDate.getFullYear(), m=state.calDate.getMonth(), first=new Date(y,m,1); let start=first.getDay(); start=start===0?6:start-1; const days=new Date(y,m+1,0).getDate(), prev=new Date(y,m,0).getDate(), today=iso(new Date()); let h=''; for(let i=0;i<start;i++) h+=`<div class="cal-cell other"><div class="cal-num">${prev-start+i+1}</div></div>`; for(let d=1;d<=days;d++){ const ds=iso(new Date(y,m,d)); h+=`<div class="cal-cell ${ds===today?'today':''}" data-date="${ds}"><div class="cal-num">${d}</div>${postsByDate(ds).map(p=>`<span class="cal-post" style="${badgeStyle(hex('block',p.block))}">${esc(label('slot',p.slot,SLOTS[p.slot]?.[0]))}: ${esc(p.topic)}</span>`).join('')}</div>`; } const rem=(start+days)%7===0?0:7-(start+days)%7; for(let i=1;i<=rem;i++) h+=`<div class="cal-cell other"><div class="cal-num">${i}</div></div>`; return h; }
function renderBank(){ const b=state.posts.filter(p=>!p.is_deleted&&canReadPost(p)&&(!p.post_date||p.status==='idea')).sort(sortPost); layout('Банк идей',b.map(rowHtml).join('')||'<div class="empty">Нет идей</div>','Карточка идеи',postEditor()); bindPostRows(); bindPostEditor(); }
function renderMaterials(){ const rows=state.materials.filter(m=>!m.is_deleted); const list=`<div class="table-wrap"><table class="table"><thead><tr><th>Тип</th><th>Название</th><th>Ссылка</th><th>Пост</th></tr></thead><tbody>${rows.map(m=>`<tr class="${m.id===state.selectedMaterial?'selected':''}" data-mid="${m.id}"><td>${esc(label('material_type',m.material_type,m.material_type))}</td><td>${esc(m.title)}</td><td><a href="${esc(safeHref(m.url))}" target="_blank">${esc(m.url)}</a></td><td>${m.post_id?'да':'нет'}</td></tr>`).join('')}</tbody></table></div>`; layout('Материалы <button class="btn" id="newMaterialBtn">+ материал</button>',list,'Карточка материала',materialEditor()); $('#newMaterialBtn').onclick=()=>openMaterialModal(); $$('tr[data-mid]').forEach(r=>r.onclick=()=>{state.selectedMaterial=r.dataset.mid; logEvent('open_material','material',state.selectedMaterial); render();}); bindMaterialEditor(); }
function selectedMaterial(){ return state.materials.find(m=>m.id===state.selectedMaterial)||state.materials[0]; }
function materialEditor(){ const m=selectedMaterial(); if(!m) return '<div class="empty">Выберите материал</div>'; return `<div class="grid2"><div class="form-row"><label>Тип</label><select id="matType">${opts('material_type',m.material_type,{link:'Ссылка',image:'Картинка',document:'Документ',video:'Видео',presentation:'Презентация',spreadsheet:'Таблица'})}</select></div><div class="form-row"><label>Пост</label><select id="matPost"><option value="">Без привязки</option>${state.posts.filter(canReadPost).map(p=>`<option value="${p.id}" ${p.id===m.post_id?'selected':''}>${esc((p.post_date||'без даты')+' · '+p.topic.slice(0,60))}</option>`).join('')}</select></div></div><div class="form-row"><label>Название</label><input id="matTitle" value="${esc(m.title||'')}"></div><div class="form-row"><label>Ссылка</label><input id="matUrl" value="${esc(m.url||'')}"></div><div class="form-row"><label>Описание</label><textarea id="matDesc">${esc(m.description||'')}</textarea></div><div class="save-line"><button class="btn danger" id="matDelete">Удалить</button><button class="btn primary" id="matSave">Сохранить материал</button></div>`; }
function bindMaterialEditor(){ $('#matSave')?.addEventListener('click',()=>saveMaterial(selectedMaterial()?.id)); $('#matDelete')?.addEventListener('click',()=>deleteMaterial(selectedMaterial()?.id)); }
function openMaterialModal(id=null,postId=null){ const m=id?state.materials.find(x=>x.id===id):{id:null,material_type:'link',title:'',url:'',description:'',post_id:postId||''}; $('#materialModalBody').innerHTML=`<form id="quickMatForm"><div class="grid2"><div class="form-row"><label>Тип</label><select id="qMatType">${opts('material_type',m.material_type,{link:'Ссылка',image:'Картинка',document:'Документ',video:'Видео'})}</select></div><div class="form-row"><label>Пост</label><select id="qMatPost"><option value="">Без привязки</option>${state.posts.filter(canReadPost).map(p=>`<option value="${p.id}" ${p.id===m.post_id?'selected':''}>${esc((p.post_date||'без даты')+' · '+p.topic.slice(0,60))}</option>`).join('')}</select></div></div><div class="form-row"><label>Название</label><input id="qMatTitle" value="${esc(m.title)}"></div><div class="form-row"><label>URL</label><input id="qMatUrl" value="${esc(m.url)}" required></div><div class="form-row"><label>Описание</label><textarea id="qMatDesc">${esc(m.description)}</textarea></div><div class="save-line"><button class="btn" type="button" data-close="materialModal">Отмена</button><button class="btn primary">Сохранить</button></div></form>`; $('#quickMatForm').onsubmit=async e=>{e.preventDefault(); await saveMaterial(null,true); closeModal('materialModal');}; openModalEl('materialModal'); }
async function saveMaterial(id,quick=false){ const payload={material_type:$(quick?'#qMatType':'#matType').value,post_id:$(quick?'#qMatPost':'#matPost').value||null,title:$(quick?'#qMatTitle':'#matTitle').value.trim(),url:$(quick?'#qMatUrl':'#matUrl').value.trim(),description:$(quick?'#qMatDesc':'#matDesc').value.trim(),owner:state.profile.display_name||state.user.email,user_id:state.user.id,is_deleted:false,updated_at:new Date().toISOString()}; const q=id?state.sb.from(TABLES.materials).update(payload).eq('id',id).select().single():state.sb.from(TABLES.materials).insert(payload).select().single(); const {data,error}=await q; if(error){toast(error.message,'error'); await logError(error,'saveMaterial'); return;} state.materials=state.materials.filter(m=>m.id!==(id||data.id)); state.materials.unshift(data); state.selectedMaterial=data.id; await logEvent(id?'save_material':'create_material','material',data.id,payload); toast('Материал сохранён','ok'); render(); }
async function deleteMaterial(id){ if(!id||!confirm('Удалить материал?'))return; const {error}=await state.sb.from(TABLES.materials).update({is_deleted:true,updated_at:new Date().toISOString()}).eq('id',id); if(error){toast(error.message,'error');return;} state.materials=state.materials.filter(m=>m.id!==id); await logEvent('delete_material','material',id); render(); }
function renderDicts(){ const cats={block:'Блоки',hashtags:'Хэштеги',slot:'Слоты',status:'Статусы',format:'Форматы',audience:'Аудитории',material_type:'Типы материалов'}; const chips=Object.entries(cats).map(([k,v])=>`<button class="btn ${state.dictCategory===k?'primary':''}" data-cat="${k}">${v}</button>`).join(''); const list=state.dictCategory==='hashtags'?tagList():dictList(); const editor=state.dictCategory==='hashtags'?tagEditor():dictEditor(); layout('Справочники',`<div style="padding:8px;display:flex;gap:6px;flex-wrap:wrap">${chips}<button class="btn accent" id="newDictBtn">+ значение</button></div>${list}`,'Карточка значения',editor); $$('[data-cat]').forEach(b=>b.onclick=()=>{state.dictCategory=b.dataset.cat;state.selectedDict=null;state.selectedTag=null;render();}); $('#newDictBtn').onclick=()=> state.dictCategory==='hashtags'?newTag():newDict(); $$('tr[data-did]').forEach(r=>r.onclick=()=>{state.selectedDict=r.dataset.did;render();}); $$('tr[data-tid]').forEach(r=>r.onclick=()=>{state.selectedTag=r.dataset.tid;render();}); bindDictEditor(); }
function dictList(){ const arr=dictItems(state.dictCategory); return `<div class="table-wrap"><table class="table"><thead><tr><th>Ключ</th><th>Название</th><th>Цвет</th><th>Сорт.</th></tr></thead><tbody>${arr.map(d=>`<tr data-did="${d.id}" class="${d.id===state.selectedDict?'selected':''}"><td>${esc(d.item_key)}</td><td>${esc(d.label)}</td><td>${esc(d.color_hex||'')}</td><td>${d.sort_order}</td></tr>`).join('')}</tbody></table></div>`; }
function tagList(){ return `<div class="table-wrap"><table class="table"><thead><tr><th>Блок</th><th>Хэштег</th><th>Цвет</th><th>Сорт.</th></tr></thead><tbody>${state.tags.map(t=>`<tr data-tid="${t.id}" class="${t.id===state.selectedTag?'selected':''}"><td>${esc(label('block',t.block,t.block))}</td><td>${esc(t.hashtag)}</td><td>${esc(t.color_hex||'')}</td><td>${t.sort_order}</td></tr>`).join('')}</tbody></table></div>`; }
function selectedDict(){ return state.dicts.find(d=>d.id===state.selectedDict)||dictItems(state.dictCategory)[0]; }
function selectedTag(){ return state.tags.find(t=>t.id===state.selectedTag)||state.tags[0]; }
function dictEditor(){ const d=selectedDict(); if(!d) return '<div class="empty">Выберите значение</div>'; return `<div class="grid2"><div class="form-row"><label>Категория</label><input id="dCat" value="${esc(d.category)}"></div><div class="form-row"><label>Ключ</label><input id="dKey" value="${esc(d.item_key)}"></div></div><div class="form-row"><label>Название</label><input id="dLabel" value="${esc(d.label)}"></div><div class="grid2"><div class="form-row"><label>HEX</label><input id="dColor" value="${esc(d.color_hex||'')}"></div><div class="form-row"><label>Сортировка</label><input id="dSort" type="number" value="${esc(d.sort_order||0)}"></div></div><div class="form-row"><label>Описание</label><textarea id="dDesc">${esc(d.description||'')}</textarea></div><div class="save-line"><button class="btn danger" id="deleteDict">Удалить</button><button class="btn primary" id="saveDict">Сохранить</button></div>`; }
function tagEditor(){ const t=selectedTag(); if(!t) return '<div class="empty">Выберите хэштег</div>'; return `<div class="grid2"><div class="form-row"><label>Блок</label><select id="tBlock">${opts('block',t.block,BLOCKS)}</select></div><div class="form-row"><label>Хэштег</label><input id="tHash" value="${esc(t.hashtag)}"></div></div><div class="form-row"><label>Название</label><input id="tTitle" value="${esc(t.title||'')}"></div><div class="grid2"><div class="form-row"><label>HEX</label><input id="tColor" value="${esc(t.color_hex||'')}"></div><div class="form-row"><label>Сортировка</label><input id="tSort" type="number" value="${esc(t.sort_order||0)}"></div></div><div class="form-row"><label>Описание</label><textarea id="tDesc">${esc(t.description||'')}</textarea></div><div class="save-line"><button class="btn danger" id="deleteTag">Удалить</button><button class="btn primary" id="saveTag">Сохранить</button></div>`; }
function bindDictEditor(){ $('#saveDict')?.addEventListener('click',saveDict); $('#deleteDict')?.addEventListener('click',deleteDict); $('#saveTag')?.addEventListener('click',saveTag); $('#deleteTag')?.addEventListener('click',deleteTag); }
function newDict(){ const d={id:'new',category:state.dictCategory,item_key:'new_value',label:'Новое значение',description:'',color_hex:'#1f5f5b',is_active:true,sort_order:999}; state.dicts.unshift(d); state.selectedDict='new'; render(); }
function newTag(){ const t={id:'new',block:'help',hashtag:'#новый_тег',title:'',description:'',color_hex:'#1f5f5b',is_active:true,sort_order:999}; state.tags.unshift(t); state.selectedTag='new'; render(); }
async function saveDict(){ const id=selectedDict()?.id; const payload={category:$('#dCat').value,item_key:$('#dKey').value,label:$('#dLabel').value,description:$('#dDesc').value,color_hex:$('#dColor').value,is_active:true,sort_order:Number($('#dSort').value||0)}; const q=id==='new'?state.sb.from(TABLES.dicts).insert(payload).select().single():state.sb.from(TABLES.dicts).update(payload).eq('id',id).select().single(); const {data,error}=await q; if(error){toast(error.message,'error');return;} state.dicts=state.dicts.filter(x=>x.id!==id); state.dicts.push(data); state.selectedDict=data.id; await logEvent('save_dictionary','dictionary',data.id,payload); render(); }
async function deleteDict(){ const id=selectedDict()?.id; if(!id||id==='new'||!confirm('Удалить значение?')) return; const {error}=await state.sb.from(TABLES.dicts).delete().eq('id',id); if(error){toast(error.message,'error');return;} state.dicts=state.dicts.filter(x=>x.id!==id); state.selectedDict=null; await logEvent('delete_dictionary','dictionary',id); render(); }
async function saveTag(){ const id=selectedTag()?.id; let h=$('#tHash').value.trim(); if(!h.startsWith('#')) h='#'+h; const payload={block:$('#tBlock').value,hashtag:h,title:$('#tTitle').value,description:$('#tDesc').value,color_hex:$('#tColor').value,is_active:true,sort_order:Number($('#tSort').value||0)}; const q=id==='new'?state.sb.from(TABLES.tags).insert(payload).select().single():state.sb.from(TABLES.tags).update(payload).eq('id',id).select().single(); const {data,error}=await q; if(error){toast(error.message,'error');return;} state.tags=state.tags.filter(x=>x.id!==id); state.tags.push(data); state.selectedTag=data.id; await logEvent('save_hashtag','hashtag',data.id,payload); render(); }
async function deleteTag(){ const id=selectedTag()?.id; if(!id||id==='new'||!confirm('Удалить хэштег?')) return; const {error}=await state.sb.from(TABLES.tags).delete().eq('id',id); if(error){toast(error.message,'error');return;} state.tags=state.tags.filter(x=>x.id!==id); state.selectedTag=null; await logEvent('delete_hashtag','hashtag',id); render(); }
function renderAccess(){ if(!canManage()){ $('#workspace').innerHTML='<div class="empty">Нет доступа</div>'; return;} const list=`<div class="table-wrap"><table class="table"><thead><tr><th>Email</th><th>Имя</th><th>Роль</th><th>Видит</th><th>Активен</th></tr></thead><tbody>${state.profiles.map(u=>`<tr data-uid="${u.id}" class="${u.id===state.selectedUser?'selected':''}"><td>${esc(u.email)}</td><td>${esc(u.display_name||'')}</td><td>${esc(u.role)}</td><td>${esc(u.data_scope)}</td><td>${u.is_active?'да':'нет'}</td></tr>`).join('')}</tbody></table></div>`; layout('Пользователи <button class="btn" id="newUserBtn">+ пользователь</button>',list,'Карточка доступа',userEditor()); $('#newUserBtn').onclick=newUser; $$('tr[data-uid]').forEach(r=>r.onclick=()=>{state.selectedUser=r.dataset.uid;render();}); $('#saveUser')?.addEventListener('click',saveUser); $('#deleteUser')?.addEventListener('click',deleteUser); $('#genUserPassword')?.addEventListener('click',generateUserPassword); $('#copyUserPassword')?.addEventListener('click',()=>copyText($('#uPassword').value)); $('#createAuthUser')?.addEventListener('click',createAuthUserFromAccessCard); $('#resetAuthPassword')?.addEventListener('click',resetAuthPasswordFromAccessCard); }
function selectedUser(){ return state.profiles.find(u=>u.id===state.selectedUser)||state.profiles[0]; }
function newUser(){ const u={id:'new',email:'',display_name:'',role:'viewer',data_scope:'own',is_active:true,can_manage_users:false,can_read_posts:true,can_edit_posts:false,can_read_ideas:true,can_edit_ideas:false,can_read_hashtags:true,can_edit_hashtags:false,can_read_materials:true,can_edit_materials:false,can_read_dictionaries:true,can_edit_dictionaries:false,allowed_hashtags:[]}; state.profiles.unshift(u); state.selectedUser='new'; render(); }
function readUserCardPayload(){
  const payload={
    email:$('#uEmail').value.trim().toLowerCase(),
    display_name:$('#uName').value.trim(),
    role:$('#uRole').value,
    data_scope:$('#uScope').value,
    is_active:$('#uActive').value==='true',
    allowed_hashtags:$$('[data-user-tag]:checked').map(x=>x.dataset.userTag),
    updated_at:new Date().toISOString()
  };
  $$('[data-perm]').forEach(x=>payload[x.dataset.perm]=x.checked);
  return payload;
}
function userEditor(){
  const u=selectedUser();
  if(!u) return '<div class="empty">Выберите пользователя</div>';
  const checks=[['can_read_posts','Читать план'],['can_edit_posts','Редактировать план'],['can_read_ideas','Читать идеи'],['can_edit_ideas','Редактировать идеи'],['can_read_hashtags','Читать хэштеги'],['can_edit_hashtags','Редактировать хэштеги'],['can_read_materials','Читать материалы'],['can_edit_materials','Редактировать материалы'],['can_read_dictionaries','Читать справочники'],['can_edit_dictionaries','Редактировать справочники'],['can_manage_users','Управлять пользователями']];
  return `<div class="grid2"><div class="form-row"><label>Email</label><input id="uEmail" value="${esc(u.email)}" placeholder="user@company.kz"></div><div class="form-row"><label>Имя</label><input id="uName" value="${esc(u.display_name||'')}"></div></div>
  <div class="grid3"><div class="form-row"><label>Роль</label><select id="uRole"><option ${u.role==='viewer'?'selected':''}>viewer</option><option ${u.role==='editor'?'selected':''}>editor</option><option ${u.role==='admin'?'selected':''}>admin</option></select></div><div class="form-row"><label>Видимость</label><select id="uScope"><option value="own" ${u.data_scope==='own'?'selected':''}>своё</option><option value="all" ${u.data_scope==='all'?'selected':''}>всё</option></select></div><div class="form-row"><label>Активен</label><select id="uActive"><option value="true" ${u.is_active?'selected':''}>да</option><option value="false" ${!u.is_active?'selected':''}>нет</option></select></div></div>
  <div class="perm-grid">${checks.map(([k,l])=>`<label class="check"><input type="checkbox" data-perm="${k}" ${u[k]?'checked':''}>${l}</label>`).join('')}</div>
  <div class="section-label" style="margin-top:8px">Доступные хэштеги</div><div class="tag-grid">${state.tags.map(t=>`<label class="check"><input type="checkbox" data-user-tag="${esc(t.hashtag)}" ${u.allowed_hashtags?.includes(t.hashtag)?'checked':''}>${esc(t.hashtag)}</label>`).join('')}</div>
  <div class="admin-auth-box"><div class="section-label">Auth-аккаунт и пароль</div><div class="hint">Создание и сброс пароля работают через Supabase Edge Functions. Service role key хранится только на стороне Supabase, не в браузере.</div><div class="grid2"><div class="form-row"><label>Сгенерированный пароль</label><input id="uPassword" value="" readonly placeholder="нажми «Сгенерировать»"></div><div class="form-row"><label>Действия</label><div class="inline-actions"><button class="btn" id="genUserPassword" type="button">Сгенерировать</button><button class="btn" id="copyUserPassword" type="button">Копировать</button></div></div></div><div class="inline-actions auth-actions"><button class="btn accent" id="createAuthUser" type="button">Создать аккаунт + доступ</button><button class="btn" id="resetAuthPassword" type="button">Сбросить пароль</button></div><div id="authAdminResult" class="message compact"></div></div>
  <div class="save-line"><button class="btn danger" id="deleteUser">Удалить профиль доступа</button><button class="btn primary" id="saveUser">Сохранить доступ</button></div>`;
}
function generateUserPassword(){ $('#uPassword').value=generatePassword(16); $('#authAdminResult').textContent='Пароль сгенерирован. Его можно скопировать и передать пользователю.'; }
async function createAuthUserFromAccessCard(){
  try{
    const payload=readUserCardPayload();
    if(!payload.email) throw new Error('Укажи email пользователя.');
    if(!$('#uPassword').value) generateUserPassword();
    const password=$('#uPassword').value;
    if(!confirm(`Создать/синхронизировать Auth-аккаунт для ${payload.email} и сохранить доступы?`)) return;
    $('#authAdminResult').textContent='Создание аккаунта...';
    const result=await invokeAdminFunction('pulse-admin-create-user',{profile:payload,password});
    if(result.profile){ state.profiles=state.profiles.filter(x=>x.id!==selectedUser()?.id && String(x.email).toLowerCase()!==String(result.profile.email).toLowerCase()); state.profiles.push(result.profile); state.selectedUser=result.profile.id; }
    await logEvent('admin_create_auth_user','profile',result.profile?.id||null,{email:payload.email,mode:result.mode});
    $('#authAdminResult').innerHTML=`Готово: ${esc(result.mode||'created')}. Временный пароль: <b>${esc(password)}</b>`;
    toast('Аккаунт создан/синхронизирован','ok'); render();
  }catch(e){ $('#authAdminResult').textContent=e.message; toast(e.message,'error'); await logError(e,'createAuthUserFromAccessCard'); }
}
async function resetAuthPasswordFromAccessCard(){
  try{
    const email=$('#uEmail').value.trim().toLowerCase();
    if(!email) throw new Error('Укажи email пользователя.');
    if(!$('#uPassword').value) generateUserPassword();
    const password=$('#uPassword').value;
    if(!confirm(`Сбросить пароль для ${email}?`)) return;
    $('#authAdminResult').textContent='Сброс пароля...';
    const result=await invokeAdminFunction('pulse-admin-reset-password',{email,password});
    await logEvent('admin_reset_auth_password','profile',selectedUser()?.id||null,{email});
    $('#authAdminResult').innerHTML=`Пароль сброшен. Новый пароль: <b>${esc(password)}</b>`;
    toast('Пароль сброшен','ok');
  }catch(e){ $('#authAdminResult').textContent=e.message; toast(e.message,'error'); await logError(e,'resetAuthPasswordFromAccessCard'); }
}
async function saveUser(){ const id=selectedUser()?.id; const payload=readUserCardPayload(); if(!payload.email){toast('Укажи email','error');return;} const q=id==='new'?state.sb.from(TABLES.profiles).insert(payload).select().single():state.sb.from(TABLES.profiles).update(payload).eq('id',id).select().single(); const {data,error}=await q; if(error){toast(error.message,'error');return;} state.profiles=state.profiles.filter(x=>x.id!==id); state.profiles.push(data); state.selectedUser=data.id; await logEvent('save_user_access','profile',data.id,payload); render(); }
async function deleteUser(){ const id=selectedUser()?.id; if(!id||id==='new'||!confirm('Удалить профиль доступа?'))return; const {error}=await state.sb.from(TABLES.profiles).delete().eq('id',id); if(error){toast(error.message,'error');return;} state.profiles=state.profiles.filter(x=>x.id!==id); state.selectedUser=null; await logEvent('delete_user_access','profile',id); render(); }
async function renderLogs(){ if(!canManage()){ $('#workspace').innerHTML='<div class="empty">Нет доступа</div>'; return;} const {data,error}=await state.sb.from(TABLES.logs).select('*').order('created_at',{ascending:false}).limit(300); if(error){ $('#workspace').innerHTML=`<div class="empty">${esc(error.message)}</div>`; return;} const rows=data||[]; $('#workspace').innerHTML=`<section class="panel" style="height:calc(100vh - 162px)"><div class="panel-head"><div class="panel-title">Логи</div></div><div class="panel-body"><table class="table"><thead><tr><th>Время</th><th>Email</th><th>Действие</th><th>Сущность</th><th>Детали</th></tr></thead><tbody>${rows.map(l=>`<tr><td>${esc(l.created_at)}</td><td>${esc(l.email)}</td><td>${esc(l.action)}</td><td>${esc(l.entity||'')}</td><td>${esc(JSON.stringify(l.details||{}))}</td></tr>`).join('')}</tbody></table></div></section>`; }
function openPostModal(date=null){ $('#postModalBody').innerHTML=`<form id="newPostForm" class="modal-content"><div class="form-row"><label>Тема</label><input id="newTopic" required></div><div class="grid2"><div class="form-row"><label>Дата</label><input id="newDate" type="date" value="${esc(date||iso(nextMonday()))}"></div><div class="form-row"><label>Слот</label><select id="newSlot">${opts('slot','morning',SLOTS)}</select></div></div><div class="grid2"><div class="form-row"><label>Блок</label><select id="newBlock">${opts('block','help',BLOCKS)}</select></div><div class="form-row"><label>Хэштег</label><select id="newHash">${tagOptions('help')}</select></div></div><div class="form-row"><label>Цель</label><input id="newGoal"></div><div class="save-line"><button class="btn" type="button" data-close="postModal">Отмена</button><button class="btn primary">Добавить</button></div></form>`; $('#newBlock').onchange=()=>$('#newHash').innerHTML=tagOptions($('#newBlock').value); $('#newPostForm').onsubmit=async e=>{ e.preventDefault(); await createPost(); closeModal('postModal'); }; openModalEl('postModal'); }
async function createPost(){ const p=normalize({user_id:state.user.id,post_date:$('#newDate').value||null,slot:$('#newSlot').value,block:$('#newBlock').value,hashtag:$('#newHash').value,topic:$('#newTopic').value.trim(),goal:$('#newGoal').value.trim(),format:'текст',cta:'',audience:'менеджеры / кураторы / филиалы',status:'idea',owner:state.profile.display_name||state.user.email,content_text:'',notes:'',is_deleted:false,sort_order:state.posts.length+1}); const payload={...postPayload(p),user_id:state.user.id}; const {data,error}=await state.sb.from(TABLES.posts).insert(payload).select().single(); if(error){toast(error.message,'error');return;} state.posts.push(normalize(data)); state.selectedPost=data.id; await logEvent('create_post','post',data.id,payload); render(); }
async function seedPlan(){ if(!confirm('Создать базовые посты на 3 недели от ближайшего понедельника?')) return; const start=nextMonday(); const rows=[]; for(let w=1;w<=3;w++){ PLAN.forEach((r,i)=>{ const [week,day,slot,block,hashtag,topic,goal,format,cta]=r; const idx={Пн:0,Вт:1,Ср:2,Чт:3,Пт:4,Сб:5,Вс:6}[day]; const d=new Date(start); d.setDate(start.getDate()+(w-1)*7+idx); rows.push({...postPayload(normalize({post_date:iso(d),slot,block,hashtag,topic,goal,format,cta,audience:'менеджеры / кураторы / филиалы',status:'idea',owner:state.profile.display_name||state.user.email,is_deleted:false,sort_order:rows.length+1})),user_id:state.user.id}); }); } const {data,error}=await state.sb.from(TABLES.posts).insert(rows).select(); if(error){toast(error.message,'error');return;} state.posts.push(...(data||[]).map(normalize)); await logEvent('seed_plan','post',null,{count:rows.length}); render(); }
function openDayDrawer(ds){ state.drawerDate=ds; const list=postsByDate(ds); $('#drawerTitle').textContent=`${dayRu(ds)} · ${ds}`; $('#drawerSub').textContent=`${list.length} пост(ов)`; $('#drawerBody').innerHTML=list.length?list.map(dayCard).join(''):'<div class="empty">Нет постов</div>'; $('#addPostToDayBtn').onclick=()=>openPostModal(ds); $('#saveDayBtn').onclick=()=>saveDay(ds); openModalEl('dayDrawer'); $$('.drawer [data-dpost-field]').forEach(el=>el.onchange=()=>editPostField(el.dataset.id,el.dataset.dpostField,el.value)); logEvent('open_day','calendar',null,{date:ds}); }
function dayCard(p){ return `<div class="day-card" style="border-top-color:${hex('block',p.block)}"><div class="day-card-head"><div><div class="topic">${esc(p.topic)}</div><div class="hashtag">${esc(p.hashtag)}</div></div><button class="btn" onclick="window.PulseSelectPost('${p.id}')">Открыть</button></div><div class="day-section"><div class="form-row"><label>Слот</label><select data-id="${p.id}" data-dpost-field="slot">${opts('slot',p.slot,SLOTS)}</select></div></div><div class="day-section"><div class="form-row"><label>Статус</label><select data-id="${p.id}" data-dpost-field="status">${opts('status',p.status,STATUS)}</select></div></div><div class="day-section"><div class="form-row"><label>Блок</label><select data-id="${p.id}" data-dpost-field="block">${opts('block',p.block,BLOCKS)}</select></div></div><div class="day-section text"><div class="grid2"><div class="form-row"><label>Текст</label><textarea data-id="${p.id}" data-dpost-field="content_text">${esc(p.content_text||'')}</textarea></div><div class="form-row"><label>Заметки</label><textarea data-id="${p.id}" data-dpost-field="notes">${esc(p.notes||'')}</textarea></div></div></div></div>`; }
window.PulseSelectPost=id=>{ state.selectedPost=id; closeModal('dayDrawer'); switchTab('plan'); };
async function saveDay(ds){ const ids=postsByDate(ds).map(p=>p.id).filter(id=>state.dirty.has(id)); for(const id of ids) await savePost(id); $('#drawerStatus').textContent='Сохранено'; }
function openExcelModal(){ state.excelPage=1; $('#excelModalBody').innerHTML=excelModalHtml(); openModalEl('excelModal'); bindExcelModal(); updateExcelPreview(); logEvent('open_excel_export','export'); }
function excelModalHtml(){ return `<div class="modal-content"><div class="excel-filters"><label>Дата с<input id="xlFrom" type="date"></label><label>Дата по<input id="xlTo" type="date"></label><label>Хэштег<select id="xlHash"><option value="all">Все</option>${state.tags.map(t=>`<option>${esc(t.hashtag)}</option>`).join('')}</select></label><label>Статус<select id="xlStatus"><option value="all">Все</option>${dictItems('status').map(s=>`<option value="${s.item_key}">${esc(s.label)}</option>`).join('')}</select></label><label>Блок<select id="xlBlock"><option value="all">Все</option>${dictItems('block').map(b=>`<option value="${b.item_key}">${esc(b.label)}</option>`).join('')}</select></label><label>Слот<select id="xlSlot"><option value="all">Все</option>${dictItems('slot').map(s=>`<option value="${s.item_key}">${esc(s.label)}</option>`).join('')}</select></label><label>Материалы<select id="xlMat"><option value="all">Все</option><option value="yes">Да</option><option value="no">Нет</option></select></label></div><div class="excel-preview-box"><div class="excel-preview-head"><span id="xlPreviewInfo" class="hint"></span><div class="pager"><button class="btn" id="xlPrev">← назад</button><span id="xlPage" class="hint"></span><button class="btn" id="xlNext">вперёд →</button></div></div><div class="excel-table-scroll"><table class="excel-preview-table" id="xlTable"></table></div></div><div class="save-line"><span class="hint">Фильтры применяются к preview и к файлу.</span><button class="btn primary" id="xlExport">Скачать Excel</button></div></div>`; }
function bindExcelModal(){ ['xlFrom','xlTo','xlHash','xlStatus','xlBlock','xlSlot','xlMat'].forEach(id=>$('#'+id).oninput=()=>{state.excelPage=1;updateExcelPreview();}); $('#xlPrev').onclick=()=>{state.excelPage=Math.max(1,state.excelPage-1);updateExcelPreview();}; $('#xlNext').onclick=()=>{state.excelPage++;updateExcelPreview();}; $('#xlExport').onclick=exportExcel; }
function excelRows(){ const f={from:$('#xlFrom')?.value||'',to:$('#xlTo')?.value||'',hash:$('#xlHash')?.value||'all',status:$('#xlStatus')?.value||'all',block:$('#xlBlock')?.value||'all',slot:$('#xlSlot')?.value||'all',mat:$('#xlMat')?.value||'all'}; return state.posts.filter(p=>!p.is_deleted&&canReadPost(p)).filter(p=>!f.from||p.post_date>=f.from).filter(p=>!f.to||p.post_date<=f.to).filter(p=>f.hash==='all'||p.hashtag===f.hash).filter(p=>f.status==='all'||p.status===f.status).filter(p=>f.block==='all'||p.block===f.block).filter(p=>f.slot==='all'||p.slot===f.slot).filter(p=>{const has=state.materials.some(m=>m.post_id===p.id&&!m.is_deleted); return f.mat==='all'||(f.mat==='yes'?has:!has);}).sort(sortPost).map(excelRow); }
function excelRow(p){ const ms=state.materials.filter(m=>m.post_id===p.id&&!m.is_deleted); return {'ID':p.id,'Неделя':p.week_no,'Дата':p.post_date,'День недели':p.day_name,'Слот':label('slot',p.slot,SLOTS[p.slot]?.[0]),'Блок':label('block',p.block,BLOCKS[p.block]),'Хэштег':p.hashtag,'Тема':p.topic,'Цель':p.goal,'Формат':p.format,'Аудитория':p.audience,'CTA':p.cta,'Статус':label('status',p.status,STATUS[p.status]),'Автор / владелец':p.owner,'Текст поста':p.content_text,'Заметки':p.notes,'Материалы: есть':ms.length?'Да':'Нет','Материалы: названия':ms.map(m=>m.title).join(' | '),'Материалы: ссылки':ms.map(m=>m.url).join(' | '),'Материалы: типы':ms.map(m=>label('material_type',m.material_type,m.material_type)).join(' | '),'Материалы: описания':ms.map(m=>m.description).join(' | '),'Создано':p.created_at,'Обновлено':p.updated_at}; }
function updateExcelPreview(){ const rows=excelRows(), page=Math.max(1,state.excelPage), per=20, total=Math.max(1,Math.ceil(rows.length/per)); state.excelPage=Math.min(page,total); const slice=rows.slice((state.excelPage-1)*per,state.excelPage*per); const cols=Object.keys(slice[0]||excelRow({})); $('#xlPreviewInfo').textContent=`Найдено: ${rows.length}. Показано: ${slice.length}.`; $('#xlPage').textContent=`${state.excelPage} / ${total}`; $('#xlPrev').disabled=state.excelPage<=1; $('#xlNext').disabled=state.excelPage>=total; $('#xlTable').innerHTML=`<thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${slice.map(r=>`<tr>${cols.map(c=>`<td title="${esc(r[c]||'')}">${esc(r[c]||'')}</td>`).join('')}</tr>`).join('')}</tbody>`; }
async function exportExcel(){ const rows=excelRows(); if(!rows.length){toast('Нет строк для выгрузки','error');return;} const ws=XLSX.utils.json_to_sheet(rows); ws['!cols']=Object.keys(rows[0]).map(k=>({wch:k==='ID'?14:k==='Материалы: ссылки'?24:Math.min(34,Math.max(10,k.length+4))})); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Pulse export'); XLSX.writeFile(wb,`eurasia_on_pulse_${iso(new Date())}.xlsx`); await logEvent('export_excel','export',null,{count:rows.length}); }
function openModalEl(id){ $('#'+id).classList.remove('hidden'); }
function closeModal(id){ $('#'+id).classList.add('hidden'); }
